.ds Vv 1.2.14
.TH VistaIONumber 3 "19 January 1993" "VistaIO Version \*(Vv"
.SH NAME
VistaIONumber - determine the number of array elements
.SH SYNTAX
.nf
.B "#include <vistaio.h>"
.PP
.ft B
size_t VistaIONumber (\fIarray\fP)
.RS
ArrayVariable \fIarray\fP;
.RE
.fi
.SH ARGUMENTS
.IP \fIarray\fP 10n
Specifies a fixed-size array.
.SH DESCRIPTION
The \fBVistaIONumber\fP macro returns the number of elements in the specified
array (computed as the size of the array divided by the size of an array
element).
.SH "SEE ALSO"

.SH NOTES
It is equivalent to the X Toolkit macro \fBXtNumber\fP(3Xt).
