.ds VistaIOn 2.1
.TH VistaIOBandInterp 3Vi "24 April 1993" "Vista VistaIOersion \*(VistaIOn"
.SH NAME
VistaIOImageFrameInterp, VistaIOImageViewpointInterp, VistaIOImageColorInterp, VistaIOImageComponentInterp \- image band interpretation
.SH SYNOPSIS
.nf
.B #include <vistaio.h>
.PP
.B VistaIOBandInterp VistaIOImageFrameInterp (VistaIOImage \fIimage\fP)
.PP
.B VistaIOBandInterp VistaIOImageViewpointInterp (VistaIOImage \fIimage\fP)
.PP
.B VistaIOBandInterp VistaIOImageColorInterp (VistaIOImage \fIimage\fP)
.PP
.B VistaIOBandInterp VistaIOImageComponentInterp (VistaIOImage \fIimage\fP)
.PP
.ft B
.ta 4n 30n
typedef enum {
	VistaIOBandInterpNone,	/* no interpretation */
	VistaIOBandInterpOther,	/* unknown interpretation */
	VistaIOBandInterpStereoPair,	/* describing camera viewpoints */
	VistaIOBandInterpRGB,	/* describing color channels */
	VistaIOBandInterpComplex,	/* describing vector components */
	VistaIOBandInterpGradient,
	VistaIOBandInterpIntensity,
	VistaIOBandInterpOrientation
} VistaIOBandInterp;
.DT
.SH ARGUMENTS
.IP \fIimage\fP 10n
Specifies an image for which band interpretation information is sought.
.SH DESCRIPTION
These four routines return information about how an image's bands are to be 
interpreted. Each reports on one of four band interpretation dimensions: 
motion sequence frame, camera viewpoint, color channel, or vector 
component. 
.SH "RETURN VALUES"
Each routine examines the size of its respective dimension (e.g., 
\fBnframes\fP), plus any band interpretation attribute for its dimension 
(e.g., \fBframe_interp\fP) and returns a value based on them. Specifically:
.IP \(bu 2n
if the size of the dimension is 1 and there is no band interpretation
attribute, it returns \fBVistaIOBandInterpNone\fP
.IP \(bu
\fBVistaIOImageViewpointInterp\fP returns \fBVistaIOBandInterpStereoPair\fP if
\fIimage\fP is a standard stereo pair (i.e., \fBnviewpoints:\ 2\fP and
\fBviewpoint_interp: stereo_pair\fP)
.IP \(bu
\fBVistaIOImageColorInterp\fP returns \fBVistaIOBandInterpRGB\fP if \fIimage\fP is a
standard RGB color image (i.e., \fBncolors:\ 3\fP and \fBcolor_interp:
rgb\fP)
.IP \(bu
\fBVistaIOImageComponentInterp\fP returns \fBVistaIOBandInterpComplex\fP if \fIimage\fP 
is a standard complex image (i.e., \fBncomponents:\ 2\fP and 
\fBcomponent_interp: complex\fP) 
.IP \(bu
\fBVistaIOImageComponentInterp\fP returns \fBVistaIOBandInterpGradient\fP if
\fIimage\fP is a standard gradient image (i.e., \fBncomponents:\ 1\fP or
\fB2\fP, and \fBcomponent_interp: gradient\fP)
.IP \(bu
\fBVistaIOImageComponentInterp\fP returns \fBVistaIOBandInterpIntensity\fP if 
\fIimage\fP is a standard intensity image (i.e., \fBncomponents:\ 1\fP and 
\fBcomponent_interp: intensity\fP) 
.IP \(bu
\fBVistaIOImageComponentInterp\fP returns \fBVistaIOBandInterpOrientation\fP if 
\fIimage\fP is a standard orientation image (i.e., \fBncomponents:\ 1\fP 
and \fBcomponent_interp: orientation\fP) 
.IP \(bu
each routine returns \fBVistaIOBandInterpOther\fP otherwise
.SH "SEE ALSO"
.BR VistaIOSetBandInterp (3Vi),
.BR VistaIOImage (3Vi),

.SH DIAGNOSTICS
A warning is issued and VistaIOBandInterpOther is returned if a dimension's size 
(e.g., \fBncolors\fP) and the corresponding band interpretation attribute 
(e.g., \fBcolor_interp\fP) are inconsistent. 
.PP
A warning is also issued if the product of the four dimension's sizes does
not equal the total number of bands in the image.
.SH AUTHOR
Art Pope <pope@cs.ubc.ca>
