.ds Vv 1.2.14
.TH VistaIONew 3 "24 April 1993" "VistaIO Version \*(Vv"
.SH NAME
VistaIONew \- allocate storage for an instance of a data type
.SH SYNOPSIS
.PP
.ft B
.nf
#include <vistaio.h>
.ft
.fi
.PP
.ft B
.nf
\fItype\fP *VistaIONew (\fItype\fP)
.ft
.RS
.B \fItype\fP;
.RE
.fi
.SH ARGUMENTS
.IP \fItype\fP 10n
Specifies a previously declared data type.
.SH DESCRIPTION
\fBVistaIONew\fP allocates storage for one instance of a data type. It is 
a convenience macro that calls \fBVistaIOMalloc\fP(3) with the following
arguments specified:
.PP
.RS
.nf
.B ((\fItype\fP *) VistaIOMalloc (sizeof (\fItype\fP))
.fi
.RE
.SH "RETURN VALUES"
\fBVistaIONew\fP returns a pointer to the allocated storage.
.SH "SEE ALSO"
.na
.nh
.BR VistaIOMalloc (3),
.BR VistaIONewString (3),
.BR VistaIOError (3),

.ad
.hy
.SH DIAGNOSTICS
If there is insufficient memory to allocate the new block, \fBVistaIONew\fP
terminates by calling \fBVistaIOError\fP(3) with the message ``Out of memory''.
.SH AUTHOR
Art Pope <pope@cs.ubc.ca>

Adaption to vistaio: Gert Wollny <gw.fossdev@gmail.com>
.SH ACKNOWLEDGMENT
This macro and this manual page are based on similar ones
included in the X Toolkit Intrinsics, which is 
Copyright 1985, 1986, 1987, 1988
Massachusetts Institute of Technology, Cambridge, Massachusetts,
and Digital Equipment Corporation, Maynard, Massachusetts.
