.ds Vv 1.2.14
.TH VistaIOSameImage 3 "24 April 1993" "VistaIO Version \*(Vv"
.SH NAME
VistaIOSameImageRange, VistaIOSameImageSize \- test whether two images share certain properties
.SH SYNOPSIS
.nf
.B "#include <vistaio.h>"
.PP
.ft B
VistaIOBoolean VistaIOSameImageRange (\fIimage1\fP, \fIimage2\fP)
.RS
VistaIOImage \fIimage1\fP, \fIimage2\fP;
.RE
.PP
.ft B
VistaIOBoolean VistaIOSameImageSize (\fIimage1\fP, \fIimage2\fP)
.RS
VistaIOImage \fIimage1\fP, \fIimage2\fP;
.RE
.fi
.SH ARGUMENTS
.IP "\fIimage1\fP, \fIimage2\fP" 10n
Specify the images whose properties are to be compared.
.SH DESCRIPTION
\fBVistaIOSameImageRange\fP returns
.SB TRUE
if \fIimage1\fP and \fIimage2\fP have the
same number of bands, rows, and columns, and the same pixel representation;
it returns
.SB FALSE
otherwise.
.PP
\fBVistaIOSameImageSize\fP returns 
.SB TRUE
if \fIimage1\fP and \fIimage2\fP have the same
number of bands, rows, and columns; it returns 
.SB FALSE
otherwise.
.PP
Both are macros defined in \fB<vistaio.h>\fP.
.SH "SEE ALSO"
.BR VistaIOImage (3),

.SH AUTHOR
Art Pope <pope@cs.ubc.ca>

Adaption to vistaio: Gert Wollny <gw.fossdev@gmail.com>
