.ds VistaIOn 2.1
.TH VistaIOGetPixel 3 "24 April 1993" "Vista VistaIOersion \*(VistaIOn"
.SH NAME
VistaIOGetPixel, VistaIOSetPixel \- get and set pixel values
.SH SYNOPSIS
.nf
.B #include <vistaio.h>
.PP
.ft B
VistaIODouble VistaIOGetPixel (\fIimage\fP, \fIband\fP, \fIrow\fP, \fIcolumn\fP)
.RS
VistaIOImage \fIimage\fP;
int \fIband\fP, \fIrow\fP, \fIcolumn\fP;
.RE
.PP
.ft B
void VistaIOSetPixel (\fIimage\fP, \fIband\fP, \fIrow\fP, \fIcolumn\fP, \fIvalue\fP)
.RS
VistaIOImage \fIimage\fP;
int \fIband\fP, \fIrow\fP, \fIcolumn\fP;
VistaIODouble \fIvalue\fP;
.fi
.SH ARGUMENTS
.IP \fIimage\fP 10n
Specifies the image containing the pixel.
.IP "\fIband\fP, \fIrow\fP, \fIcolumn\fP"
Specify the band, row, and column of the pixel.
.IP \fIvalue\fP
Specifies the pixel's new value.
.SH DESCRIPTION
\fBVistaIOGetPixel\fP fetches the value of the specified pixel and returns it as
a \fBVistaIODouble\fP, casting it from the image's actual pixel representation
if necessary.
.PP
\fBVistaIOSetPixel\fP sets the specified pixel to \fIvalue\fP, casting it to 
the image's actual pixel representation if necessary.
.SH "RETURN VALUES"
\fBVistaIOGetPixel\fP returns the value of the specified pixel.
.SH "SEE ALSO"
.BR VistaIOImage (3),

.SH NOTES
If the image is known to have a particular pixel representation then the
\fBVistaIOPixel\fP macro (see \fBVistaIOImage\fP(3)) can be used, instead, yielding
greater efficiency.
.SH AUTHOR
Art Pope <pope@cs.ubc.ca>

Adaption to vistaio: Gert Wollny <gw.fossdev@gmail.com>
