.ds VistaIOn 2.1
.TH VistaIOOffset 3Vi "19 January 1993" "Vista VistaIOersion \*(VistaIOn"
.SH NAME
VistaIOOffset, VistaIOOffsetOf \- determine the byte offset of a structure field
.SH SYNTAX
.nf
.B "#include <vista/mu.h>"
.PP
.ft B
size_t VistaIOOffset (\fIpointer_type\fP, \fIfield_name\fP)
.RS
Type \fIpointer_type\fP;
Field \fIfield_name\fP;
.RE
.PP
.ft B
size_t VistaIOOffsetOf (\fIstruct_type\fP, \fIfield_name\fP)
.RS
Type \fIstruct_type\fP;
Field \fIfield_name\fP;
.RE
.fi
.SH ARGUMENTS
.IP \fIfield_name\fP 10n
Specifies the name of a structure field for which to calculate the byte
offset.
.IP \fIpointer_type\fP
Specifies a type that is declared as a pointer to a structure.
.IP \fIstruct_type\fP
Specifies a type that is declared as a structure.
.SH DESCRIPTION
The \fBVistaIOOffset\fP and \fBVistaIOOffsetOf\fP macros return the byte offset of the
\fIfield_name\fP field within its structure.
.SH "SEE ALSO"
.BR VistaIOlib (7Vi)
.SH NOTES
These are equivalent to the X Toolkit macros \fBXtOffset\fP(3Xt) and
\fBXtOffsetOf\fP(3Xt). ANSI C defines an \fBoffsetof\fP macro, which is to
be preferred over any of these.
