.ds VistaIOn 2.1
.TH VistaIOSetProgramName 3Vi "24 April 1993" "Vista VistaIOersion \*(VistaIOn"
.SH NAME
VistaIOSetProgramName \- register a program name for error messages
.SH SYNOPSIS
.nf
.ft B
void VistaIOSetProgramName (\fIname\fP)
.RS
VistaIOStringConst \fIname\fP
.RE
.fi
.SH ARGUMENTS
.IP \fIname\fP 10n
Specifies the program's name as a null-terminated string, or is 
.SB NULL
to indicate that no program name should be registered.
.SH DESCRIPTION
\fBVistaIOSetProgramName\fP determines what, if any, program name will be
included in subsequent error messages composed by \fBVistaIOError\fP (3Vi),
\fBVistaIOSystemError\fP(3Vi), \fBVistaIOWarning\fP(3Vi), and \fBVistaIOSystemWarning\fP(3Vi).
.PP
Initially, no program name is registered. If \fBVistaIOSetProgramName\fP
is called with a string, that string is registered as the program name. 
If \fBVistaIOSetProgramName\fP is called with an argument of 
.SM NULL\c
, any previously-registered name is forgotten.
.SH EXAMPLES
.RS
.nf
.ft B
int main (argc, argv)
int argc;
char *argv[];
{
	\fR...\fP
	VistaIOSetProgramName (argv[0]);
	\fR...\fP
}
.fi
.RE
.SH "SEE ALSO"
.na
.nh
.BR VistaIOError (3Vi),
.BR VistaIOWarning (3Vi),
.BR VistaIOSetErrorHandler (3Vi),
.BR VistaIOSetWarningHandler (3Vi),

.ad
.hy
.SH NOTES
\fBVistaIOSetProgramName\fP does not make its own copy of the string it is passed.
Consequently, storage used for the string must be maintained by the caller.
.SH AUTHOR
Art Pope <pope@cs.ubc.ca>

Adaption to vistaio: Gert Wollny <gw.fossdev@gmail.com>
