.ds VistaIOn 2.1
.TH VistaIOCopy 3Vi "19 January 1993" "Vista VistaIOersion \*(VistaIOn"
.SH NAME
VistaIOCopy, VistaIOZero - copy or zero an array
.SH SYNTAX
.nf
.B "#include <vistaio.h>"
.PP
.ft B
void VistaIOCopy (\fIfrom\fP, \fIto\fP, \fInels\fP)
.RS
\fItype\fP *\fIfrom\fP, *\fIto\fP;
size_t \fInels\fP;
.RE
.PP
.ft B
void VistaIOZero (\fIarray\fP, \fInels\fP)
.RS
\fItype\fP *\fIarray\fP;
size_t \fInels\fP;
.RE
.fi
where \fItype\fP is any C type.
.SH ARGUMENTS
.IP "\fIfrom\fP, \fIto\fP, \fIarray\fP" 10n
Each specifies a pointer to the first element of an array of \fItype\fP.
.IP \fInels\fP
Specifies the number of array elements.
.SH DESCRIPTION
The \fBVistaIOCopy\fP macro copies \fInels\fP array elements (each of type
\fItype\fP) from \fIfrom\fP to \fIto\fP.
.PP
The \fBVistaIOZero\fP macro writes zeros into \fInels\fP array elements (each of
type \fItype\fP) beginning at \fIarray\fP.
.SH "SEE ALSO"

