.ds Vv 1.2.14
.TH VistaIOPrintParameters 3 "6 June 1994" "VistaIO Version \*(Vv"
.SH NAME
VistaIOPrintParameters \- print the values of a set of parameters
.SH SYNOPSIS
.B #include <vistaio.h>
.HP 10n
.na
.nh
.ft B
void VistaIOPrintParameters (FILE\ *\fIf\fP, 
int\ \fInparams\fP,
VistaIOOptionDescRec\ \fIparams\fP[],
VistaIOPointer\ \fIvalues\fP);
.ft
.hy
.ad
.SH ARGUMENTS
.IP \fIf\fP 10n
Specifies the stream to which the parameters are to be printed.
.IP \fInparams\fP
Specifies the number of entries in the table of option descriptors.
.IP \fIparams\fP
Specifies a table of option descriptors. Each entry describes one parameter.
.IP \fIvalues\fP
Specifies the location of the structure containing the parameter values.
.SH DESCRIPTION
\fBVistaIOPrintParameters\fP prints the names, descriptions, and values of a set
of parameters.
.PP
The parameters are described by a table of option descriptors (see
\fBVistaIOoption\fP(3)).
.PP
Parameter values must be stored in the structure pointed to by \fIvalues\fP.
The offset at which a parameter lies within that structure must be supplied
by the \fIvalue\fP field of the parameter's \fIparams\fP table entry.
Appropriate definitions having this property are produced by the \fBvpdc\fP
compiler.
.SH "SEE ALSO"
.na
.nh
.BR VistaIOoption (3),
.BR VistaIOLoadParameters (3),
.BR VistaIOParseParamOptions (3),
.BR VistaIOReportValidParamOptions (3)

.hy
.ad
.SH AUTHOR
Art Pope <pope@cs.ubc.ca>

Adaption to vistaio: Gert Wollny <gw.fossdev@gmail.com>
